### ISSUE TITLE
Thread usage

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.TypeProviders.StarterPack#109]
Just simple question:
- There is a lot of type providers dealing with network connections.
- It seems that Visual Studio is quite unresponsive while connecting (or a lot network traffic happens).

Would VS be able to take advantage of async or System.Threading.Tasks? 
So that instead of ProvidedTypes.fsi signatures returning an unit, they could return a Task or Async.

I don't want my provided types be Task<'a>, I just want VS to be responsive.

**Comment by sergey-tihon** [comment]
VS calls TP mode often than you have to generate new provided types or do network call.
I think that a good practice is to use MemoryCache on TP side and don't generate schema too often.
In each particular case caching logic may be different... See for example how @vasily-kirichenko do it in `FSharp.Configuration` - https://github.com/fsprojects/FSharp.Configuration/blob/master/src/FSharp.Configuration/YamlConfigProvider.fs#L489

**Comment by Thorium** [comment]
The problem is also that VS has a lot of threads and I've already seen many not-so-good implementations of caching, done somehow incorrectly and I don't blame the developers: concurrent caching is easy to get wrong. Most of the developers are not having strong enterprise background and are not so familiar with correct use of ConcurrentDictionaries, lazy, avoiding locks, etc. The problem is that you don't even notice what VS is doing in the background, and VS debugging is not so pleasant either, also needing a fast computer. Then when you use a few TPs combined in a real life, you just wonder why Windows says your VS is "busy", and taking a huge amount of memory.

Vasily's code is good. (If we expect that you don't have large Yamls: there is no cache cleanup for his concurrent dictionary.)

**Comment by dsyme** [comment]
Closing old discussion
