### ISSUE TITLE
Error compiling ProvidedTypes.fs - 'ExpectedStackState' is less accessible

### ISSUE THREAD

**Issue by ptrelford** [fsprojects/FSharp.TypeProviders.StarterPack#113]
### Description

I followed tip 1 in Sergey Tihon's blog entry [F# Type Providers Development Tips (not Tricks)](https://sergeytihon.wordpress.com/2016/07/11/f-type-providers-development-tips-not-tricks/) where you can create a new type provider by including providedtypes.fs/fsi from this starter pack using paket.
### Repro steps

When I compile the project using Visual Studio 2015, the F# compiler gives the following error:

`paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fs(1082,15): error FS0410: The type 'ExpectedStackState' is less accessible than the value, member or type 'member CodeGenerator.EmitExpr : expectedState:ExpectedStackState * expr:Expr -> unit' it is used in`
### Expected behavior

The code should compile.
### Actual behavior

The code doesn't compile.
### Known workarounds

Revert to an older version of the providetypes.fs/fsi files
### Related information
- Windows 10
- .NET Runtime 4.0 & 4.5

**Comment by sergey-tihon** [comment]
could you share you `paket.dependencies` and `paket.lock` files?

**Comment by ptrelford** [comment]
@sergey-tihon thanks for looking at this, this is what I generated today.

paket.dependencies

```
source https://nuget.org/api/v2

github fsprojects/FSharp.TypeProviders.StarterPack src/ProvidedTypes.fsi 
github fsprojects/FSharp.TypeProviders.StarterPack src/ProvidedTypes.fs
```

paket.lock

```
GITHUB
  remote: fsprojects/FSharp.TypeProviders.StarterPack
  specs:
    src/ProvidedTypes.fs (dbbfb58d1238bf21c84c455451501c7f31ae95e1)
    src/ProvidedTypes.fsi (dbbfb58d1238bf21c84c455451501c7f31ae95e1)
```

**Comment by sergey-tihon** [comment]
I repeated it by myself and it works with following lock file
```
GITHUB
  remote: fsprojects/FSharp.TypeProviders.StarterPack
    src/ProvidedTypes.fs (dbbfb58d1238bf21c84c455451501c7f31ae95e1)
    src/ProvidedTypes.fsi (dbbfb58d1238bf21c84c455451501c7f31ae95e1)
```

**Comment by sergey-tihon** [comment]
@ptrelford Could you share your `*.fsproj` file? Interesting is `Fsharp.Core.dll`, framework, and order of `fs`/`fsi`

**Comment by ptrelford** [comment]
@sergey-tihon interesting, this is what I have:

```
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFSharpCoreVersion>4.4.0.0</TargetFSharpCoreVersion>
    ...
    <Content Include="paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fsi">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fsi</Link>
    </Content>
    <Compile Include="paket-files\fsprojects\FSharp.TypeProviders.StarterPack\src\ProvidedTypes.fs">
      <Paket>True</Paket>
      <Link>paket-files/ProvidedTypes.fs</Link>
    </Compile>
    ...
    <Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <Private>True</Private>
    </Reference>
```

**Comment by sergey-tihon** [comment]
It looks good... Just updated TP SDK in SwaggerProvider - https://github.com/fsprojects/SwaggerProvider/pull/53 (it works on my machine)

**Comment by ptrelford** [comment]
@sergey-tihon thanks, I have also managed to get it working on another machine, with what appears to be a slightly older version of Visual F#.

This is version giving the compiler error:
> Microsoft Visual Studio Professional 2015
> Version 14.0.24720.00 Update 1
> Microsoft .NET Framework
> Version 4.6.01038
> Installed Version: Professional
> 
> Visual F# 2015   00322-40000-00000-AA595
> Microsoft Visual F# 2015

**Comment by sergey-tihon** [comment]
On my machine everything is OK with
![image](https://cloud.githubusercontent.com/assets/1197905/18606170/0f5cfaf2-7cb0-11e6-8fb7-38670e7fa2e4.png)

**Comment by mavnn** [comment]
Looks like a merge for this got fixed; closing.
