### ISSUE TITLE
ProvidedMethod with static parameters in generative TP "does not have an invoker "

### ISSUE THREAD

**Issue by Lleutch** [fsprojects/FSharp.TypeProviders.StarterPack#125]
### Description
The issue is the following:
I am working on a generative TP, and I am trying to generate _non-static providedMethods with static parameters_.

However I have 2 cases where this is not working : 
- either I have add the generated types to a temporary assembly like : 
```
let assemblyPath = Path.ChangeExtension(System.IO.Path.GetTempFileName(), ".dll")
let assembly = ProvidedAssembly assemblyPath
assembly.AddTypes [ty]
``` 
However, I get a compilation error : 

> ProvidedMethod: no invoker for ExampleMethWithStaticParam on type GenerativeTypeProviderExample.Provided.Example

- 2nd solution, I can remove those 3 lines from the code, therefore I don't have any compilation error any longer.
However I get a runtime error of the form : 

> internal error: null: convTypeRefAux 

### Repro steps

To reproduce the error the following step should make it happen : 
1. Go to the following https://github.com/Lleutch/StaticMethodGTP and clone it
2. Compile it on VS, it doesn't work currently with the fake script (I didn't took the time to make the fake script work for the repro repo. If that's necessary just tell me about it and I will do it 🙂 )
3. go to Examples/Examples.fsx and this is a small example using the TP where you'll see the issue.
4. (Optional) Comment/Uncomment the 3 lines mentionned in comments in `Library1.fs` to have either of the two issues.

### Expected behavior

I should be able to generate types that are not erased at run-time and that can contain these non-static provided methods with static parameters.

The reason for having made the choice of a generative TP, comes from the fact that this TP is used to include session-types in F#, and within session-types the branching choice mechanism is something that relies on run-time receive branching which makes it "necessary" to have the types generated. 

### Known workarounds

I haven't found any workaround.

### Related information 

* Operating system : Windows 10
* .NET Runtime, CoreCLR or Mono Version : .Net framework 4.5

If there is any information that might be lacking there, please do not hesitate to ask me i'll do my best to help.

Thank you in Advance for your time.

**Comment by ReedCopsey** [comment]
I'm not sure if the static parameter support was intended to work on generative type providers. All of the examples I've seen (and samples from original repository) were on erased...

**Comment by Lleutch** [comment]
After a discussion on twitter with @dsyme : https://twitter.com/dsyme/status/895588269265571841 , we now know that for generative TPs it is not possible to have static parametrized method.
It is possible for erased TPs though.

I will then close the issue as we know that it is not feasible for generative TPs.
:slightly_smiling_face:
