### ISSUE TITLE
Parameter names mismatch.

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FSharp.TypeProviders.StarterPack#127]
### Description

`Visual Studio for Mac` use parameter manes from `fsi` file, compiler and other IDEs use names from `fs` files, so it is hard to work on TP using `Visual Studio for Mac`

### Repro steps

![vscode-vs-vs4mac](https://user-images.githubusercontent.com/1197905/29686765-df723d68-8922-11e7-96f1-b63e5355e870.png)

### Expected behavior

We need to unify parameter names across fs and fsi files.

### Question

@dsyme May I update `ProviderTypes.fsi` using parameter names from `ProvidedTypes.fs`? As I understand, this way-update does not break existing TPs.

**Comment by sergey-tihon** [comment]
Do we really need `fsi` file?

What is the general rule /technic to keep `fsi` up to date? (I see not only name mismatch, but also some public members defined in `fs` file are missed in `fsi`)

**Comment by dsyme** [comment]
@sergey-tihon I believe we will add an optional compiler warning in the compiler to check the parameter name correspondence

The technique to keep them up-to-date is purely manual today

**Comment by dsyme** [comment]
@sergey-tihon Given the messiness of the .fs file, I think we do need the FSI in this case, to give a clean, documented view of the API

**Comment by sergey-tihon** [comment]
@dsyme what the source of truth for the compiler?

Should I
1. Copy parameter names from `fsi` to `fs` 
1. Copy parameter names from `fs` to `fsi`

Option 1 (from `fsi` to `fs`) look correct but would be better to confirm.

**Comment by sergey-tihon** [comment]
@nosami How this may happen that `VS for Mac` is the only IDE that uses parameter names from `fs` file that `fsi` is available?

**Comment by nosami** [comment]
@sergey-tihon : No idea. I'm currently on vacation until Tuesday, so I will take a look into it then. Is the error just inside the IDE? Build works ok?

The only explanations that I can think of are that either VS for Mac isn't passing in the path to the `.fsi` files to the compiler, or something has changed in the compiler itself.

**Comment by sergey-tihon** [comment]
@nosami yes, build is ok, the error just inside IDE.

No rush with it, have a nice vacation!

**Comment by sergey-tihon** [comment]
Fixed by #128 at least for SwaggerProvider
