### ISSUE TITLE
Discussion: Public access to assemblyMainModule

### ISSUE THREAD

**Issue by TIHan** [fsprojects/FSharp.TypeProviders.StarterPack#14]
I noticed here: https://github.com/mavnn/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypes.fs#L1372 that this is the ModuleBuilder for the generated assembly. With what I know, which is little, this is the type that allows us to build everything we want for a given assembly.

That in mind, I'm wondering if it is ok to allow public access to assemblyMainModule, meaning when building a type provider I can gain access to the main module when I have constructed my ProvidedAssembly for a generative type-provider. This would allow full control of what you can build in the generated assembly without having to go through the abstractions, such as ProvidedTypeDefinition, ProvidedMethod, etc. and adding them via. AddType/AddTypes

The use case I had was I wanted to generate PInvokeMethods, but there were no abstractions for that or anything related to emitting "calli" ops. The only way to do it is through the ModuleBuilder type then the TypeBuilder type.

Is this reasonable? If not, should we just keep creating abstractions/extensions for things we don't have yet, such as PInvokeMethods?

I've made the changes myself to see how it works; and it works like I intended and am able to generate PInvokeMethods. The question is whether it is a good idea to allow access. The downside of allowing access is that anyone building a type-provider could do it in a completely, non-standard way. The upside is that it can handle use cases that the abstractions don't cover yet.

Take this with a grain of salt. This is just one use case I found, and I don't know if it is the only one. If it is the only one, then making an abstraction might be a better option instead of public access to the assemblyMainModule.

**Comment by dsyme** [comment]
Closing as it's old and discussion over
