### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by mavnn** [fsprojects/FSharp.TypeProviders.StarterPack#29]
I've added a simple smoke test to make sure that ProvidedTypes.fs compiles, but we need some tests adding.

**Comment by mavnn** [comment]
Closed via fccda84970d0866c8600f9302090d240ee97ea14

**Comment by vladima** [comment]
Back in days when ProvidedTypes API was hosted on codeplex I've added a bunch of tests to verify that type providers generate correct and verifiable code: [TypeProviders.fs](http://fsharp3sample.codeplex.com/SourceControl/latest#SampleProviders/Samples.Tests/TypeProviders/TypeProviders.fs) and [Clients.fs](http://fsharp3sample.codeplex.com/SourceControl/latest#SampleProviders/Samples.Tests/Clients/Clients.fs). It will be nice to port them as well

**Comment by mavnn** [comment]
Excellent. It should be quite straight forward to include these. Thanks!
