### ISSUE TITLE
AddXmlDocComputed is not adding xml docs

### ISSUE THREAD

**Issue by bruinbrown** [fsprojects/FSharp.TypeProviders.StarterPack#46]
Taken from [Stackoverflow question](http://stackoverflow.com/questions/22507381/usage-of-addxmldoccomputed-in-an-f-type-provider)

I have a type provider which provides a static property but the documentation is subject to change at recurring intervals throughout. I have the following property setup.

```
let prop = ProvidedProperty("Test", typeof<string>,
                            IsStatic = true,
                            GetterCode = fun args -> <@@ "Test" @@>)
```

I then tried to add some documentation to it with AddXmlDocComputed as follows

```
let GetDocumentation () = "Test documentation"

do prop.AddXmlDocComputed(GetDocumentation)  
```

However, I get no text displayed in the Intellisense comments. I then raised an exception in the `GetDocumentation` function which is reflected in the intellisense through the addition of the `[<Note>]` and the message saying that it originated from the call to `GetDocumentation`. I also tried using `AddXmlDoc` and `AddXmlDocDelayed`, both of which added the documentation as expected.

So this leads to my question of does anyone have any experience using `AddXmlDocComputed` and why does my current implementation add no documentation to the property?

Edit:
I've now tried debugging a VS2013 instance and can see that the documentation is being called and the expected string is being passed through the type provider for that property, however, there is still no documentation appearing in the Intellisense window.

**Comment by matiasdd** [comment]
I believe the problem is that computed attributes are never returned by `__.GetCustomAttributeData()` in `type CustomAttributesImpl()` .

The implementation reads:

    member __.GetCustomAttributesData() = 
            [| yield! customAttributesOnce.Force()
               match xmlDocAlwaysRecomputed with None -> () | Some f -> customAttributes.Add(mkXmlDocCustomAttributeData (f()))  |]

but should read:

    member __.GetCustomAttributesData() = 
            [| yield! customAttributesOnce.Force()
               match xmlDocAlwaysRecomputed with None -> () | Some f -> yield mkXmlDocCustomAttributeData (f())  |]
            :> IList<_>
