### ISSUE TITLE
DefineStaticParameters method on ProvidedMethod 

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.StarterPack#57]
To enable 
https://github.com/dsyme/SampleMethStaticParamProvider

prototyped here 
https://github.com/dsyme/SampleMethStaticParamProvider/blob/master/src/SampleMethStaticParamProvider/ProvidedTypes.fsi#L115

**Comment by sergey-tihon** [comment]
Are you going to do PR?

**Comment by dsyme** [comment]
I'm working on this

**Comment by mavnn** [comment]
Closed with #58 , I believe.
