### ISSUE TITLE
Support F# 4.0 features

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/FSharp.TypeProviders.StarterPack#59]
@dsyme is there any changes required in this starter pack to support F# 4.0 features for Type Providers?

**Comment by xperiandri** [comment]
@pezipink, any progress?

**Comment by sergey-tihon** [comment]
As I understand this issue is duplicate for https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/57
and PR with changes is here https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/58

**Comment by pezipink** [comment]
I was not implementing this for the starter pack :) I am innocent of all charges!

**Comment by mavnn** [comment]
I believe #58 adds this. Please re-open if that wasn't what you were expecting!
