### ISSUE TITLE
Unwrapped inner exception related to ProvidedMethod.DefineStaticParameters

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.StarterPack#63]
When exception is thrown in body of ```instantiationFunction``` passed to ProvidedMethod.DefineStaticParameters it shows up in user code as 
"The type provider ... reported an error: Exception has been thrown by the target of an invocation..." 
An actual error message is hidden from user which makes this feature almost unusable. 

I'm not sure whether it requires the compiler or FSharp.TypeProviders.StarterPack fix.
//cc @dsyme

**Comment by KevinRansom** [comment]
@dmitry-a-morozov would you be able to provide a small repro.  It would save us some time.

**Comment by dmitry-a-morozov** [comment]
@KevinRansom Sure.

**Comment by KevinRansom** [comment]
Thank you

**Comment by dmitry-a-morozov** [comment]
Here you go
https://github.com/dmitry-a-morozov/SampleMethStaticParamProvider/commits/FSharp-TypeProviders-StarterPack-issues-63

It's based on Don's original sample project.
In diff ignore upgrade to the version 1.1.3.72 of FSharp.TypeProviders.StarterPack. 
Pay attention to a small change in TypeProvider.fs and test script Script.fsx.
To test just hit F5. 

Key line to repro is
https://github.com/dmitry-a-morozov/SampleMethStaticParamProvider/blob/569e8ba8139beffa5c72631cb164dfcbc65dc893/src/SampleMethStaticParamProvider/Script.fsx#L9

**Comment by KevinRansom** [comment]
Excellent thank you, I will take a look.

**Comment by dsyme** [comment]
This should be fixed by PR #703 above
