### ISSUE TITLE
Method overloads based on same set of static method params

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.StarterPack#64]
How do I add overloads based on same set of method static parameters?
Let's say I want ```ExampleMethWithStaticParam``` accept either int or float
https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/StaticMethodArgumentsDesignAndSpec.md
```FSharp
let x = ExampleType()

let v1int = x.ExampleMethWithStaticParam<1>(1) 

//???
let v1float = x.ExampleMethWithStaticParam<1>(1.1) 
```

//cc @dsyme @KevinRansom

**Comment by dsyme** [comment]
As discussed on twitter, this can't be done (it would be an F# language feature request, though in truth  I don't think we would add support for this)
