### ISSUE TITLE
Generative types support for statically parameterized type provider methods

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsprojects/FSharp.TypeProviders.StarterPack#68]
Currently I get this compilation error

Severity	Code	Description	Project	File	Line
Severity	Code	Description	Project	File	Line
Error		A problem occurred writing the binary 'C:\Users\mitekm\Documents\GitHub\SampleMethStaticParamProvider\tests\SampleMethStaticParamProvider.Tests\obj\Debug\SampleMethStaticParamProvider.Tests.dll': Error in pass3 for type SampleMethStaticParamProvider.Tests, error: Error in GetMethodRefAsMethodDefIdx for mref = (".ctor", "ExampleType"), error: Exception of type 'Microsoft.FSharp.Compiler.AbstractIL.ILBinaryWriter+MethodDefNotFound' was thrown.	SampleMethStaticParamProvider.Tests	FSC	1

Repro
https://github.com/dmitry-a-morozov/SampleMethStaticParamProvider/tree/GenerativeTypes2

//cc @dsyme

**Comment by sergey-tihon** [comment]
I fixed the same error in [SwaggerProvider couple minutes ago](https://github.com/sergey-tihon/SwaggerProvider/blob/swashbuckle/src/SwaggerProvider/SwaggerProvider.fs#L61-L63) in https://github.com/sergey-tihon/SwaggerProvider/pull/7 you can see changes in SwaggerProvider.fs  that helped me.

It is probably not exactly your case by I needed to create ProvidedAssembly inside `instantiationFunction` of `DefineStaticParameters`

**Comment by dmitry-a-morozov** [comment]
No, this is something different
https://twitter.com/dsyme/status/666223246421962752

**Comment by dsyme** [comment]
Closing this as it's not technically possible (at least in F# 4.x, with no plans to add this to F# 5.x)
