### ISSUE TITLE
Unable to generate obsolete methods from generative TP

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FSharp.TypeProviders.StarterPack#70]
Seems that generative TP cannot produce methods with `Obsolete` attribute 

Here is the simple generative type provider that provide single static method
```fsharp
module ObsoleteProvider

open System.Reflection
open ProviderImplementation.ProvidedTypes
open Microsoft.FSharp.Core.CompilerServices
open Microsoft.FSharp.Quotations

[<TypeProvider>]
type public ObsoleteProvider (cfg : TypeProviderConfig) as this =
    inherit TypeProviderForNamespaces ()

    let ns = "Bug"
    let asm = Assembly.GetExecutingAssembly()
    let tempAsmPath = System.IO.Path.ChangeExtension(System.IO.Path.GetTempFileName(), ".dll")
    let tempAsm = ProvidedAssembly tempAsmPath

    let t = ProvidedTypeDefinition(asm, ns, "Obsolete", Some typeof<obj>, IsErased = false)
    let parameters = [ProvidedStaticParameter("temp", typeof<string>)]

    do
        t.DefineStaticParameters(
            parameters,
            fun typeName args ->
                let g = ProvidedTypeDefinition(asm, ns, typeName, Some typeof<obj>, IsErased = false)

                let m = ProvidedMethod("Call",[], typeof<int>, IsStaticMethod = true)
                m.InvokeCode <- fun args -> <@@3@@>
                //m.AddObsoleteAttribute("Deprecated", false)
                g.AddMember m

                tempAsm.AddTypes [g]

                g
            )

    do
        this.RegisterRuntimeAssemblyLocationAsProbingFolder cfg
        tempAsm.AddTypes [t]
        this.AddNamespace(ns, [t])

[<assembly:TypeProviderAssembly>]
do ()
```

If I execute simple usage script
```fsharp
#r "ObsoleteTypeProvider.dll"
type T = Bug.Obsolete<"">
T.Call()
```

I receive output as expected

>type T =
  class
    static member Call : unit -> int
  end
val it : int = 3

But If I uncomment line `m.AddObsoleteAttribute("Deprecated", false)` and execute the same script I receive

> demo.fsx(2,10): error FS3033: The type provider 'ObsoleteProvider+ObsoleteProvider' reported an error: Parameter count does not match passed in argument value count.

//cc @dsyme @dmitry-a-morozov @mavnn @ovatsus @pezipink

**Comment by dsyme** [comment]
Could you check if the generative DLL is produced correctly by the type provider? Or find the exception stacktrace? The bug could be in codegen in this repo, or perhaps the F# compiler. May require a bit of type provider debugging work to grab the dll from temp storage.

**Comment by sergey-tihon** [comment]
Exception occurs on this line https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypes.fs#L1841

StackTrace:
>    at System.Reflection.Emit.CustomAttributeBuilder.InitCustomAttributeBuilder(ConstructorInfo con, Object[] constructorArgs, PropertyInfo[] namedProperties, Object[] propertyValues, FieldInfo[] namedFields, Object[] fieldValues)

Seems like we are trying to call wrong `ObsoleteAttribute` constructor (that has one param)
![image](https://cloud.githubusercontent.com/assets/1197905/12442699/3d88f15c-bf63-11e5-9e04-8a6097df44d8.png)
with two arguments
![image](https://cloud.githubusercontent.com/assets/1197905/12442742/96ad5cfa-bf63-11e5-8ccc-98d19e894283.png)

Sooo, probably here 
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypes.fs#L137
should be
```fsharp
|> Array.find (fun x -> x.GetParameters().Length = 2)
```
instead of 
```fsharp
|> Array.find (fun x -> x.GetParameters().Length = 1)
```
