### ISSUE TITLE
Calling generic methods where type arguments are bound to provided types.

### ISSUE THREAD

**Issue by takemyoxygen** [fsprojects/FSharp.TypeProviders.StarterPack#91]
While working on [a generative type provider](https://github.com/takemyoxygen/ProtoTypes), I stumbled upon one interesting thing. I generated a class with a bunch of properties and I tried to generate a method that calls a function for each property, but the actual function to call depends on type of the property, one function handles regular types, another one - all `option<'a>` types, etc. As a result, when I try to create a quotation containing call of a function that takes generic `option<'a> ` as a parameter, I get `NotSupportedException` coming from `System.Reflection.Emit.TypeBuilderInstantiation.IsAssignableFrom` but only when `'a` is actually a generated type.

A simple console app to demonstrate this:
```fsharp
module Serializer =

    /// string -> 'a option -> unit
    let serializeOption name = function 
        | Some(x) -> printfn "Serializing %s: %A" name x
        | None -> printfn "%s: Absolutely nothing" name

[<EntryPoint>]
let main argv =
    let anotherTy = ProvidedTypeDefinition("Another", Some typeof<obj>, IsErased = false)
    let targetTy = ProvidedTypeDefinition(Assembly.GetExecutingAssembly(), "Some.Namespace", "Target", Some typeof<obj>, IsErased = false)

    // option<Another> type
    let anotherOptionTy = ProvidedTypeBuilder.MakeGenericType(typedefof<option<_>>, [anotherTy])

    let property = ProvidedProperty("AnotherTypeOptionProperty", anotherOptionTy, GetterCode = (fun _ -> <@@ None @@>));
    // So, now Target type has single property "AnotherTypeOptionProperty" of type option<Another>
    targetTy.AddMember property

    let serializeOptionMethodDef = 
        match <@@ Serializer.serializeOption "foo" None @@> with 
        | Call(_, m, _) -> m.GetGenericMethodDefinition()
    
    // MethodInfo for serializeOption: string -> option<Another> -> unit
    let serializeOptionMethod = ProvidedTypeBuilder.MakeGenericMethod(serializeOptionMethodDef, [anotherTy])
    
    let this = Expr.Var(Var("this", targetTy))

    // This should create a quotation <@@ Serializer.serializeOption "AnotherTypeOptionProperty" this.AnotherTypeOptionProperty @@>,
    // but fails with NotSupportedException
    Expr.Call(serializeOptionMethod, [Expr.Value(property.Name); Expr.PropertyGet(this, property)])

    // Otherwise console app would fail
    TypeProviderForNamespaces().AddNamespace("Some.Namespace", [targetTy])  
    
    0
```

Full stack trace:
```
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at System.Reflection.Emit.TypeBuilderInstantiation.IsAssignableFrom(Type c)
   at Microsoft.FSharp.Quotations.PatternsModule.checkTypesWeakSR[a](Type expectedType, Type receivedType, a name, String threeHoleSR)
   at Microsoft.FSharp.Quotations.PatternsModule.checkArgs@599.Invoke(ParameterInfo p, FSharpExpr a)
   at Microsoft.FSharp.Collections.ListModule.loop@94-18[T1,T2](FSharpFunc`3 f, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Collections.ListModule.Iterate2[T1,T2](FSharpFunc`2 action, FSharpList`1 list1, FSharpList`1 list2)
   at Microsoft.FSharp.Quotations.PatternsModule.checkArgs(ParameterInfo[] paramInfos, FSharpList`1 args)
   at Microsoft.FSharp.Quotations.PatternsModule.mkStaticMethodCall(MethodInfo minfo, FSharpList`1 args)
   at Microsoft.FSharp.Quotations.FSharpExpr.Call(MethodInfo methodInfo, FSharpList`1 arguments)
   at GenericMethodsCallsDemo.main(String[] argv) in Y:\dev\code\temp\generic-methods\GenericMethodsCallsDemo\GenericMethodsCallsDemo.fs:line 34
```

I'm using .NET 4.5 and F# 4.0 on Windows 10.
The behavior is the same on OS X with Mono 4.2.1 except for the fact that the exception is thrown by `System.Reflection.MonoGenericClass` rather than `System.Reflection.Emit.TypeBuilderInstantiation`.

Is that some kind of a known limitation of type providers? Are there any workarounds for that?

Thanks.

**Comment by sergey-tihon** [comment]
Could you try to call generic function using reflection?
https://github.com/fsprojects/FSharp.Management/blob/master/src/FSharp.Management.PowerShell/TypeInference.fs#L78
```fsharp
type CollectionConverter<'T> =
    static member Convert (objSeq:obj seq) =
        objSeq |> Seq.cast<'T> |> Seq.toList
```
https://github.com/fsprojects/FSharp.Management/blob/master/src/FSharp.Management.PowerShell/HostedRuntime.fs#L134-L141
```fsharp
  let collectionConverter =
      typedefof<CollectionConverter<_>>.MakeGenericType(tyOfObj)
  let collectionObj =
      if (tyOfObj = typeof<PSObject>) then box result
      else result |> Seq.map (fun x->x.BaseObject) |> box
  let typedCollection =
      collectionConverter.GetMethod("Convert").Invoke(null, [|collectionObj|])
```

**Comment by takemyoxygen** [comment]
@sergey-tihon, you mean to generate a method that invokes `Serializer.serializeOption` via reflection? I guess it should work, but I'd prefer avoid potential performance cost of using reflection. 

The actual problem is that it's not possible to define a function that takes `option<GeneratedType` as an argument, so the workaround I ended up implementing is to define a function that takes an `obj` instead, and internally it's casted to required type:
```
    let serializeOption2<'T> name (value: obj) = 
        if value <> null 
        then (value :?> option<'T>) |> Option.get |> printfn "Serializing %s: %A" name
        else printfn "%s: Absolutely nothing" name
```

In this case, extra run-time cost is to cast from `option<'T>` to `obj` before calling `serializeOption2` and the other way around inside `serializeOption2`.

**Comment by takemyoxygen** [comment]
Since I have a workaround and apparently this is a limitation that cannot be fixed in the scope of this project, I'm closing this issue.
